"""empty message

Revision ID: 10af3f929eb8
Revises: 2a0a29d8f843
Create Date: 2014-07-31 19:24:04.418724

"""

# revision identifiers, used by Alembic.
revision = '10af3f929eb8'
down_revision = '2a0a29d8f843'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('role', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'name')
    ### end Alembic commands ###
