"""empty message

Revision ID: 1729e25c1270
Revises: 26a9efee95ae
Create Date: 2014-08-08 08:56:03.337918

"""

# revision identifiers, used by Alembic.
revision = '1729e25c1270'
down_revision = '26a9efee95ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.add_column(u'person', sa.Column('protocol_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'person', 'protocol_id')
    op.drop_table('research_protocol')
    ### end Alembic commands ###
