"""empty message

Revision ID: 26a9efee95ae
Revises: 580bd7f83312
Create Date: 2014-08-07 14:04:57.829952

"""

# revision identifiers, used by Alembic.
revision = '26a9efee95ae'
down_revision = '580bd7f83312'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('exists', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'exists')
    ### end Alembic commands ###
