"""empty message

Revision ID: 2a0a29d8f843
Revises: 573fb018da4e
Create Date: 2014-05-28 17:26:24.441404

"""

# revision identifiers, used by Alembic.
revision = '2a0a29d8f843'
down_revision = '573fb018da4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('match_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'match_id')
    ### end Alembic commands ###
